#ABNF 1.0;
language pl-pl;
mode voice;
root $root;
tag-format <semantics/1.0-literals>;

$root = $play $songs $pause ($previous |$random |$replay |$remove | $next | $remove) |
        $play $songs ($stop |$volumeUp | $volumeDown) |
        $find $songs ($play | $remove)

$play = odtwarzaj | odtwórz | graj | puść;
$pause = pauza | zastrzymaj;
$stop = stop | wstrzymaj | wstrzymaj muzykę;
$next = (następny | następna | przewiń do przodu | pomiń | pomiń utwór | dalej) | $play (kolejny | kolejną | następną | następny);
$previous = (poprzedni | cofnij | cofnij utwór) ;
$volumeUp = (podgłośnij | głośniej);
$volumeDown = (ścisz | ciszej);
$repeat = (powtórz utwór | powtórz | ponownie);



                            $songs = ...


