#ABNF 1.0;
language pl-pl;
mode voice;
root $root;
tag-format <semantics/1.0-literals>;

$root = $command;

$command = (odtwarzaj | odtwórz | graj | puść) {play} |
           (pauza | zastrzymaj) {pause} |
           (stop | wstrzymaj | wstrzymaj muzykę) {stop} |
           (podgłośnij | głośniej) {volumeUp} |
           (ścisz | ciszej) {volumeDown} ;

